### PR TITLE
migrate to flutter v2 and add new icons

### PR DESCRIPTION
**Pull request by pushpendraKh**
icons added
- share
- whitelisted
- arow_top

resolves: #15

### CODE REVIEW

**Comment by AvazAlimov** [comment]
- Cocoapods version can be updated
- Shouldn't we need to update .flutter_version file? @pushpendraKh

**Comment by AvazAlimov** [comment]
Icons added:
- [x] share
- [x] whitelisted

**Comment by pushpendraKh** [comment]
> Cocoapods version can be updated

No need. As it is a pure dart project.

> Don't we need to update .flutter_version file?

Duh, I updated and tested on the upgraded version also but somehow missed pushing the version file change. Thanks, Avaz for bringing it up. We definitely need to update.

**Review by AvazAlimov — APPROVED** [review]

**Comment by pushpendraKh** [comment]
Will merge when we will start migration for mobilesoc_flutter project.

**Review by jfmdev — APPROVED** [review]

**Comment by AvazAlimov** [comment]
- [x] share
- [x] whitelisted
- [x] arrow_top

Good to go!

**Review by AvazAlimov — APPROVED** [review]

**Pull request merged**
